name: Python application test with pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install selenium
    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@master
    - name: Run tests with pytest
      run: |
        pytest
    env:
      CHROME_BIN: /usr/bin/google-chrome
      CHROME_PATH: /usr/lib/chromium-browser